### ISSUE TITLE
Feature−Weighted Linear Stacking or Standard Linear Stacking

### ISSUE THREAD

**Issue by ghost** [nlinc1905/Ensemble-Models-Majority-Vote-SLS#1]
Does it FWLS?
 It's look like Standard Linear Stacking. You have logistic regression estimator, witch means you have  b(x)=sum{i from 1 to n} gi(x) \* wi, where wi is weight of estimator gi for i from 1 to n. But in FWLS we have b(x)=sum{i,j} vij \* fi \* gi(x). I mean SLS is FWLS in case when wi=sum{j=1..m}wij*fj(x).
http://arxiv.org/pdf/0911.0460.pdf

**Comment by yiming-chen** [comment]
I don't think your code is an implementation of FWLS. It is only building a logistics regression on top of model predictions.

**Comment by nlinc1905** [comment]
@ghost and @yiming-chen  are right: this is an implementation of standard linear stacking using logistic regression.  It is not feature-weighted linear stacking as it was originally named.  I have updated the repository to reflect that it is SLS.
